//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uNav {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalisedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalisedStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uNav.LocalisedStrings", typeof(LocalisedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All tracks were saved to.
        /// </summary>
        internal static string MainForm_AllTracksWereSavedTo {
            get {
                return ResourceManager.GetString("MainForm_AllTracksWereSavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close application?.
        /// </summary>
        internal static string MainForm_ApplicationClosePrompt {
            get {
                return ResourceManager.GetString("MainForm_ApplicationClosePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear all tracks data?.
        /// </summary>
        internal static string MainForm_ClearAllTracksDataPrompt {
            get {
                return ResourceManager.GetString("MainForm_ClearAllTracksDataPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear current plot? This action will not change the tracks..
        /// </summary>
        internal static string MainForm_ClearCurrentPlotPrompt {
            get {
                return ResourceManager.GetString("MainForm_ClearCurrentPlotPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device information.
        /// </summary>
        internal static string MainForm_DeviceInformation {
            get {
                return ResourceManager.GetString("MainForm_DeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable automatic screenshot every 1 second? Frames will be saved to AUTOSNAPSHOTS folder.
        /// </summary>
        internal static string MainForm_EnableAutomaticScreenShotEvery1SecondQuestion {
            get {
                return ResourceManager.GetString("MainForm_EnableAutomaticScreenShotEvery1SecondQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string MainForm_Error {
            get {
                return ResourceManager.GetString("MainForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exporting tracks....
        /// </summary>
        internal static string MainForm_ExportingTracks {
            get {
                return ResourceManager.GetString("MainForm_ExportingTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frames are saved to.
        /// </summary>
        internal static string MainForm_FramesAreSavedTo {
            get {
                return ResourceManager.GetString("MainForm_FramesAreSavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        internal static string MainForm_Information {
            get {
                return ResourceManager.GetString("MainForm_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log-file.
        /// </summary>
        internal static string MainForm_LogFile {
            get {
                return ResourceManager.GetString("MainForm_LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moving average smoothing....
        /// </summary>
        internal static string MainForm_MovingAverageSmoothing {
            get {
                return ResourceManager.GetString("MainForm_MovingAverageSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Override target depth....
        /// </summary>
        internal static string MainForm_OverrideTargetDepth {
            get {
                return ResourceManager.GetString("MainForm_OverrideTargetDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Override water temperature....
        /// </summary>
        internal static string MainForm_OverrideWaterTemperature {
            get {
                return ResourceManager.GetString("MainForm_OverrideWaterTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playback....
        /// </summary>
        internal static string MainForm_Playback {
            get {
                return ResourceManager.GetString("MainForm_Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на playback is finished.
        /// </summary>
        internal static string MainForm_PlaybackIsFinished {
            get {
                return ResourceManager.GetString("MainForm_PlaybackIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Question.
        /// </summary>
        internal static string MainForm_Question {
            get {
                return ResourceManager.GetString("MainForm_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Screenshot saved to.
        /// </summary>
        internal static string MainForm_ScreenshotSavedTo {
            get {
                return ResourceManager.GetString("MainForm_ScreenshotSavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a track to filter.
        /// </summary>
        internal static string MainForm_SelectATrackToFilter {
            get {
                return ResourceManager.GetString("MainForm_SelectATrackToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select filename to save filtered track....
        /// </summary>
        internal static string MainForm_SelectFilenameToSaveFilteredTrack {
            get {
                return ResourceManager.GetString("MainForm_SelectFilenameToSaveFilteredTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specify a point to use as a refernce.
        /// </summary>
        internal static string MainForm_SpecifyAPointToUseAsAReference {
            get {
                return ResourceManager.GetString("MainForm_SpecifyAPointToUseAsAReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        internal static string MainForm_Start {
            get {
                return ResourceManager.GetString("MainForm_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        internal static string MainForm_Stop {
            get {
                return ResourceManager.GetString("MainForm_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop automatic screen shot every 1 second?.
        /// </summary>
        internal static string MainForm_StopAutomaticScreenshotEvery1SecondQuestion {
            get {
                return ResourceManager.GetString("MainForm_StopAutomaticScreenshotEvery1SecondQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target depth, m.
        /// </summary>
        internal static string MainForm_TargetDepthM {
            get {
                return ResourceManager.GetString("MainForm_TargetDepthM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Track offset....
        /// </summary>
        internal static string MainForm_TrackOffset {
            get {
                return ResourceManager.GetString("MainForm_TrackOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save tracks before exit?.
        /// </summary>
        internal static string MainForm_TracksSavePrompt {
            get {
                return ResourceManager.GetString("MainForm_TracksSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tracks successfully saved..
        /// </summary>
        internal static string MainForm_TracksSuccessfullySaved {
            get {
                return ResourceManager.GetString("MainForm_TracksSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        internal static string MainForm_Warning {
            get {
                return ResourceManager.GetString("MainForm_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Water temperature.
        /// </summary>
        internal static string MainForm_WaterTemperature {
            get {
                return ResourceManager.GetString("MainForm_WaterTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Window size.
        /// </summary>
        internal static string MainForm_WindowSize {
            get {
                return ResourceManager.GetString("MainForm_WindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X offset (Longitude), m.
        /// </summary>
        internal static string MainForm_XOffset_Longitude_m {
            get {
                return ResourceManager.GetString("MainForm_XOffset_Longitude_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Y offset (Latitude), m.
        /// </summary>
        internal static string MainForm_YOffset_Latitude_m {
            get {
                return ResourceManager.GetString("MainForm_YOffset_Latitude_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Median smoothing....
        /// </summary>
        internal static string MainFrom_MedianSmoothing {
            get {
                return ResourceManager.GetString("MainFrom_MedianSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CANCEL.
        /// </summary>
        internal static string SettingsEditor_Cancel {
            get {
                return ResourceManager.GetString("SettingsEditor_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lat.
        /// </summary>
        internal static string SettingsEditor_Lat {
            get {
                return ResourceManager.GetString("SettingsEditor_Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lon.
        /// </summary>
        internal static string SettingsEditor_Lon {
            get {
                return ResourceManager.GetString("SettingsEditor_Lon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nearest known point.
        /// </summary>
        internal static string SettingsEditor_NearestKnownPoint {
            get {
                return ResourceManager.GetString("SettingsEditor_NearestKnownPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Salinity, PSU.
        /// </summary>
        internal static string SettingsEditor_SalinityPSU {
            get {
                return ResourceManager.GetString("SettingsEditor_SalinityPSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Water salinity.
        /// </summary>
        internal static string SettingsEditor_WaterSalinity {
            get {
                return ResourceManager.GetString("SettingsEditor_WaterSalinity", resourceCulture);
            }
        }
    }
}
